# Generated by Django 3.0.8 on 2020-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='C:\\Users\\ventafri\\Desktop\\Holiday Planner\\Holiday_Planner\\holiday_planner\\media'),
        ),
    ]
