# Generated by Django 3.0.8 on 2020-07-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200715_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='C:\\Users\\ventafri\\Desktop\\Repositories\\Personal\\Holiday Planner\\Holiday_Planner\\holiday_planner\\media'),
        ),
    ]
