# Generated by Django 3.0.8 on 2020-07-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20200719_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_visited', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_visited', to='users.Profile')),
            ],
        ),
    ]
