# Generated by Django 3.0.8 on 2020-07-29 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('european_countries', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Albania', 'Albania'), ('Andorra', 'Andorra'), ('Austria', 'Austria'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Bulgaria', 'Bulgaria'), ('Croatia', 'Croatia'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Estonia', 'Estonia'), ('Faroe Islands', 'Faroe Islands'), ('Finland', 'Finland'), ('France', 'France'), ('Germany', 'Germany'), ('Gibraltar', 'Gibraltar'), ('Greece', 'Greece'), ('Holy See (Vatican City)', 'Holy See (Vatican City)'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('Ireland', 'Ireland'), ('Italy', 'Italy'), ('Latvia', 'Latvia'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macedonia', 'Macedonia'), ('Malta', 'Malta'), ('Moldova', 'Moldova'), ('Monaco', 'Monaco'), ('Netherlands', 'Netherlands'), ('Norway', 'Norway'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Romania', 'Romania'), ('Russia', 'Russia'), ('San Marino', 'San Marino'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Spain', 'Spain'), ('Svalbard', 'Svalbard'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Ukraine', 'Ukraine'), ('United Kingdom', 'United Kingdom'), ('Isle of Man', 'Isle of Man'), ('Montenegro', 'Montenegro'), ('Aland Islands', 'Aland Islands'), ('Serbia', 'Serbia')], max_length=471, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
