# Generated by Django 3.0.8 on 2020-07-29 17:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesvisited',
            name='african_countries',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Algeria', 'Algeria'), ('Angola', 'Angola'), ('Benin', 'Benin'), ('Botswana', 'Botswana'), ('British Indian Ocean Territory', 'British Indian Ocean Territory'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cameroon', 'Cameroon'), ('Cape Verde', 'Cape Verde'), ('Central African Republic', 'Central African Republic'), ('Chad', 'Chad'), ('Comoros', 'Comoros'), ('Democratic Republic of Congo', 'Democratic Republic of Congo'), ('Djibouti', 'Djibouti'), ('Egypt', 'Egypt'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'), ('Ethiopia', 'Ethiopia'), ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Ghana', 'Ghana'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ("Cote d'Ivoire", "Cote d'Ivoire"), ('Kenya', 'Kenya'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libyan Arab Jamahiriya', 'Libyan Arab Jamahiriya'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mayotte', 'Mayotte'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Namibia', 'Namibia'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Reunion', 'Reunion'), ('Rwanda', 'Rwanda'), ('Saint Helena', 'Saint Helena'), ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Senegal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Somalia', 'Somalia'), ('South Africa', 'South Africa'), ('Sudan', 'Sudan'), ('Swaziland', 'Swaziland'), ('Tanzania', 'Tanzania'), ('Togo', 'Togo'), ('Tunisia', 'Tunisia'), ('Uganda', 'Uganda'), ('British Virgin Islands', 'British Virgin Islands'), ('Western Sahara', 'Western Sahara'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=612, null=True),
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='antarctic_countries',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Antarctica', 'Antarctica'), ('Bouvet Island', 'Bouvet Island'), ('French Southern and Antarctic Lands', 'French Southern and Antarctic Lands'), ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'), ('South Georgia South Sandwich Islands', 'South Georgia South Sandwich Islands')], max_length=131, null=True),
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='asian_countries',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Afghanistan', 'Afghanistan'), ('Armenia', 'Armenia'), ('Azerbaijan', 'Azerbaijan'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Bhutan', 'Bhutan'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Cambodia', 'Cambodia'), ('China', 'China'), ('Cyprus', 'Cyprus'), ('East Timor', 'East Timor'), ('Georgia', 'Georgia'), ('Hong Kong', 'Hong Kong'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Israel', 'Israel'), ('Japan', 'Japan'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Laos', 'Laos'), ('Lebanon', 'Lebanon'), ('Macau', 'Macau'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mongolia', 'Mongolia'), ('Mjanma(Birma)', 'Mjanma(Birma)'), ('Nepal', 'Nepal'), ('North Korea', 'North Korea'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Palestine', 'Palestine'), ('Philippines', 'Philippines'), ('Qatar', 'Qatar'), ('Saudi Arabia', 'Saudi Arabia'), ('Singapore', 'Singapore'), ('South Korea', 'South Korea'), ('Sri Lanka', 'Sri Lanka'), ('Syria', 'Syria'), ('Taiwan', 'Taiwan'), ('Tajikistan', 'Tajikistan'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('United Arab Emirates', 'United Arab Emirates'), ('Uzbekistan', 'Uzbekistan'), ('Vietnam', 'Vietnam'), ('Yemen', 'Yemen')], max_length=464, null=True),
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='north_american_countries',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Anguilla', 'Anguilla'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Aruba', 'Aruba'), ('Bahamas', 'Bahamas'), ('Barbados', 'Barbados'), ('Belize', 'Belize'), ('Bermuda', 'Bermuda'), ('Canada', 'Canada'), ('Cayman Islands', 'Cayman Islands'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Dominica', 'Dominica'), ('Dominican Republic', 'Dominican Republic'), ('El Salvador', 'El Salvador'), ('Greenland', 'Greenland'), ('Grenada', 'Grenada'), ('Guadeloupe', 'Guadeloupe'), ('Guatemala', 'Guatemala'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Jamaica', 'Jamaica'), ('Martinique', 'Martinique'), ('Mexico', 'Mexico'), ('Montserrat', 'Montserrat'), ('Netherlands Antilles', 'Netherlands Antilles'), ('Nicaragua', 'Nicaragua'), ('Panama', 'Panama'), ('Puerto Rico', 'Puerto Rico'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Saint Lucia', 'Saint Lucia'), ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Turks and Caicos Islands', 'Turks and Caicos Islands'), ('United States', 'United States'), ('United States Virgin Islands', 'United States Virgin Islands')], max_length=466, null=True),
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='oceania_countries',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('American Samoa', 'American Samoa'), ('Australia', 'Australia'), ('Christmas Island', 'Christmas Island'), ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'), ('Cook Islands', 'Cook Islands'), ('Fiji', 'Fiji'), ('French Polynesia', 'French Polynesia'), ('Guam', 'Guam'), ('Kiribati', 'Kiribati'), ('Marshall Islands', 'Marshall Islands'), ('Micronesia, Federated States of', 'Micronesia, Federated States of'), ('Nauru', 'Nauru'), ('New Caledonia', 'New Caledonia'), ('New Zealand', 'New Zealand'), ('Niue', 'Niue'), ('Norfolk Island', 'Norfolk Island'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Palau', 'Palau'), ('Papua New Guinea', 'Papua New Guinea'), ('Pitcairn Islands', 'Pitcairn Islands'), ('Samoa', 'Samoa'), ('Solomon Islands', 'Solomon Islands'), ('Tokelau', 'Tokelau'), ('Tonga', 'Tonga'), ('Tuvalu', 'Tuvalu'), ('United States Minor Outlying Islands', 'United States Minor Outlying Islands'), ('Vanuatu', 'Vanuatu'), ('Wallis and Futuna Islands', 'Wallis and Futuna Islands')], max_length=394, null=True),
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='south_american_countries',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Argentina', 'Argentina'), ('Bolivia', 'Bolivia'), ('Brazil', 'Brazil'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('Falkland Islands', 'Falkland Islands'), ('French Guiana', 'French Guiana'), ('Guyana', 'Guyana'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Suriname', 'Suriname'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela')], max_length=126, null=True),
        ),
    ]
