# Generated by Django 3.0.8 on 2020-08-02 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_maps', '0002_auto_20200729_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesVisitedCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CitiesVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=200, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_maps.CitiesVisitedCountry')),
            ],
        ),
    ]
