# Generated by Django 3.0.8 on 2020-08-03 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_maps', '0003_citiesvisited_citiesvisitedcountry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citiesvisited',
            options={'verbose_name_plural': 'Cities visited checkbox multiple selections'},
        ),
        migrations.AlterModelOptions(
            name='citiesvisitedcountry',
            options={'verbose_name': 'Country visited', 'verbose_name_plural': 'Countries visited'},
        ),
        migrations.AlterModelOptions(
            name='placesvisited',
            options={'verbose_name_plural': 'Countries visited checkbox multiple selections'},
        ),
        migrations.AddField(
            model_name='citiesvisited',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
