# Generated by Django 3.0.8 on 2020-08-03 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_maps', '0006_auto_20200803_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citiesvisited',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
