# Generated by Django 3.0.8 on 2020-08-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_maps', '0007_auto_20200803_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citiesvisited',
            name='cities',
            field=models.TextField(),
        ),
    ]
