# Generated by Django 3.0.8 on 2020-08-04 16:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_maps', '0008_auto_20200804_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citiesvisited',
            name='cities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(' ', ' ')], max_length=1, null=True),
        ),
    ]
